server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    return 302 /marva/;
  }

  location /marva/util/ {
    proxy_pass http://keycloak-middleware:9401/marva/util/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /marva/ {
    try_files $uri $uri/ /marva/index.html;
  }
}
